apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
data:
  MODE:                       "frontend"
  TELEMETRY:                  "true"
  ENABLE_ID_OBFUSCATION:      "true"
  REDACT_IP_ADDRESSES:        "true"
  DB_TYPE:                    "mysql"
  DB_HOSTNAME:                "mysql.db"
  DB_NAME:                    "librespeed"
  DB_USERNAME:                "librespeed"
  DB_PORT:                    "3306"
