apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: db
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
