apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
  labels:
    app: db
type: Opaque
stringData:
  mysql-root-password: "Not4SecureProduction"
  mysql-database: "librespeed"
  mysql-user:     "librespeed"
  mysql-password: "Not4SecureProduction"
